#!/usr/bin/env bash
# fallback-data.sh — REALITY 回落域名候选表（纯数据）
#
# 格式: domain|country|tier|备注
#   tier 3 = 图书馆/大学/旅游局  4 = 社区实测通过  5 = 大厂（默认跳过，不推荐）
# 维护：扩充前先跑 tests 里的候选初筛脚本（见 vps-script-distribution 技能）；
#      本机 openssl 初筛 ≠ VPS 视角，入库后仍须 `xray-deploy fallback-test` 复核。

# ============ 回落域名候选（半自动） ============
# 格式: domain|country|tier|备注
# tier: 3=图书馆/大学/旅游局  4=社区测试过  5=大厂（默认跳过，不推荐）
# 2026-08-11 实测清理：cambridge.org=TLSv1.2、tum.de=无ALPN h2、mit.edu=http/1.1 → 移除
FALLBACK_CANDIDATES=(
  # 2026-08-17 扩充：每地区 ≥10（本机初筛通过；lovelive/waseda/gov.hk/ntu 为历史实测保留）
  # DE
  "www.germany.travel|DE|3|德国旅游局"
  "www.tu-dresden.de|DE|3|德累斯顿工大"
  "www.kit.edu|DE|3|卡尔斯鲁厄理工"
  "www.tu-berlin.de|DE|3|柏林工大"
  "www.uni-bonn.de|DE|3|波恩大学"
  "www.uni-freiburg.de|DE|3|弗赖堡大学"
  "www.uni-goettingen.de|DE|3|哥廷根大学"
  "www.deutschland.de|DE|3|德国官方门户"
  "www.bundesregierung.de|DE|3|联邦政府"
  "www.berlin.de|DE|3|柏林市"
  "www.tagesschau.de|DE|3|德国电视一台新闻"
  "www.dw.com|DE|3|德国之声"
  # GB
  "www.cam.ac.uk|GB|3|剑桥大学"
  "www.ed.ac.uk|GB|3|爱丁堡大学"
  "www.lse.ac.uk|GB|3|伦敦政经"
  "www.manchester.ac.uk|GB|3|曼彻斯特大学"
  "www.birmingham.ac.uk|GB|3|伯明翰大学"
  "www.kcl.ac.uk|GB|3|伦敦国王学院"
  "www.leeds.ac.uk|GB|3|利兹大学"
  "www.nottingham.ac.uk|GB|3|诺丁汉大学"
  "www.gov.uk|GB|3|英国政府"
  "www.nationalgallery.org.uk|GB|3|国家美术馆"
  "www.visitscotland.com|GB|3|苏格兰旅游局"
  # US
  "www.harvard.edu|US|3|哈佛大学"
  "www.stanford.edu|US|3|斯坦福大学"
  "www.caltech.edu|US|3|加州理工"
  "www.upenn.edu|US|3|宾夕法尼亚大学"
  "www.brown.edu|US|3|布朗大学"
  "www.ucla.edu|US|3|加州大学洛杉矶"
  "www.washington.edu|US|3|华盛顿大学"
  "www.nasa.gov|US|3|NASA"
  "www.usa.gov|US|3|美国政府门户"
  "www.archives.gov|US|3|国家档案馆"
  "www.npr.org|US|3|NPR"
  "www.wikipedia.org|US|4|维基百科"
  "www.cartoonbrew.com|US|4|动画行业媒体（洛杉矶，中国方向 12/12 实测 2026-09-17）"
  # CH
  "www.ethz.ch|CH|3|苏黎世联邦理工"
  "www.epfl.ch|CH|3|洛桑联邦理工"
  "www.uzh.ch|CH|3|苏黎世大学"
  "www.unibas.ch|CH|3|巴塞尔大学"
  "www.unibe.ch|CH|3|伯尔尼大学"
  "www.unisg.ch|CH|3|圣加仑大学"
  "www.unilu.ch|CH|3|卢塞恩大学"
  "www.zhaw.ch|CH|3|苏黎世应用科学大学"
  "www.parlament.ch|CH|3|瑞士议会"
  "www.swissinfo.ch|CH|3|瑞士资讯"
  "www.zuerich.com|CH|3|苏黎世旅游"
  # FR
  "www.bnf.fr|FR|3|法国国家图书馆"
  "www.france.fr|FR|3|法国官网"
  "www.culture.gouv.fr|FR|3|文化部"
  "www.elysee.fr|FR|3|爱丽舍宫"
  "www.inria.fr|FR|3|法国信息研究院"
  "www.louvre.fr|FR|3|卢浮宫"
  "www.polytechnique.edu|FR|3|巴黎综合理工"
  "www.sorbonne-universite.fr|FR|3|索邦大学"
  "www.cnrs.fr|FR|3|法国国家科研中心"
  "www.univ-nantes.fr|FR|3|南特大学"
  "www.univ-toulouse.fr|FR|3|图卢兹大学"
  # JP
  "www.japan.travel|JP|3|日本旅游局"
  "www.waseda.jp|JP|4|早稻田大学（实测 2026-08-12）"
  "www.keio.ac.jp|JP|3|庆应义塾大学"
  "www.kyoto-u.ac.jp|JP|3|京都大学"
  "www.ndl.go.jp|JP|3|国立国会图书馆"
  "www.nhk.or.jp|JP|3|NHK"
  "www.osaka-u.ac.jp|JP|3|大阪大学"
  "www.sophia.ac.jp|JP|3|上智大学"
  "www.titech.ac.jp|JP|3|东京工业大学"
  "www.tsukuba.ac.jp|JP|3|筑波大学"
  "www.kantei.go.jp|JP|3|首相官邸"
  "www.lovelive-anime.jp|JP|4|实测可用（2026-08-12）"
  "shin-ei-animation.jp|JP|4|动画制作公司（中国方向 11/12，1 探针 ICMP 失败→备选 2026-09-17）"
  "www.ritao.co|JP|4|东京企业站（中国方向 12/12 实测 2026-09-17）"
  # HK
  "www.gov.hk|HK|4|香港政府（实测 2026-08-12）"
  "www.info.gov.hk|HK|3|香港政府资讯"
  "www.hko.gov.hk|HK|3|香港天文台"
  "www.immd.gov.hk|HK|3|香港入境处"
  "www.police.gov.hk|HK|3|香港警务处"
  "www.hkpl.gov.hk|HK|3|香港公共图书馆"
  "www.hkma.gov.hk|HK|3|香港金管局"
  "www.ust.hk|HK|3|香港科技大学"
  "www.cityu.edu.hk|HK|3|香港城市大学"
  "www.hkbu.edu.hk|HK|3|香港浸会大学"
  "www.hyd.gov.hk|HK|3|香港渠务署"
  "www.tourism.gov.hk|HK|3|香港旅游事务署"
  "ani-com.hk|HK|4|香港动画媒体（中国方向 12/12 实测 2026-09-17）"
  # SG
  "www.ntu.edu.sg|SG|4|新加坡南洋理工（实测 2026-08-12）"
  "www.nus.edu.sg|SG|3|新加坡国立大学"
  "www.smu.edu.sg|SG|3|新加坡管理大学"
  "www.sutd.edu.sg|SG|3|新加坡科技设计大学"
  "www.gov.sg|SG|3|新加坡政府"
  "www.moe.gov.sg|SG|3|新加坡教育部"
  "www.mfa.gov.sg|SG|3|新加坡外交部"
  "www.nlb.gov.sg|SG|3|新加坡国家图书馆"
  "www.nparks.gov.sg|SG|3|新加坡公园局"
  "www.stb.gov.sg|SG|3|新加坡旅游局"
  "www.iras.gov.sg|SG|3|新加坡税务局"
  "www.cpf.gov.sg|SG|3|新加坡公积金局"
  # AU
  "www.australia.com|AU|3|澳大利亚旅游局"
  "www.adelaide.edu.au|AU|3|阿德莱德大学"
  "www.australia.gov.au|AU|3|澳大利亚政府"
  "www.bom.gov.au|AU|3|澳大利亚气象局"
  "www.nla.gov.au|AU|3|澳大利亚国家图书馆"
  "www.queensland.com|AU|3|昆士兰旅游"
  "www.rmit.edu.au|AU|3|RMIT"
  "www.sydney.com|AU|3|悉尼旅游"
  "www.sydney.edu.au|AU|3|悉尼大学"
  "www.unsw.edu.au|AU|3|新南威尔士大学"
  "www.uwa.edu.au|AU|3|西澳大学"
  "www.abc.net.au|AU|3|ABC"
  # TH
  "www.chula.ac.th|TH|3|朱拉隆功大学"
  "www.kmitl.ac.th|TH|3|国王理工"
  "www.mfa.go.th|TH|3|泰国外交部"
  "www.mots.go.th|TH|3|泰国旅游体育部"
  "www.kku.ac.th|TH|3|孔敬大学"
  "www.nu.ac.th|TH|3|那黎宣大学"
  "www.royalthaipolice.go.th|TH|3|泰国皇家警察"
  "www.boi.go.th|TH|3|泰国投资促进委员会"
  "www.ditp.go.th|TH|3|泰国国际贸易促进厅"
  "www.nstda.or.th|TH|3|泰国国家科技发展署"
  "www.tmd.go.th|TH|3|泰国气象局"
  "www.thairath.co.th|TH|3|泰叻报"
)
